### ISSUE TITLE
coordinate Map problem？

### ISSUE THREAD

**Issue by zhangxiaodi** [ShougangShen/Coordinate-LM#1]
I found the result is only saved y-coordinate value，then x and y are all the same.

  for b in range(class_bin):
                    if ((x_min + b * x_interval) <= coor_x[i]) and ((x_min + (b + 1) * x_interval) >= coor_x[i]):
                        data_save_x[i] = b

                    if ((y_min + b * y_interval) <= coor_y[i]) and ((y_min + (b + 1) * y_interval) >= coor_y[i]):
                        data_save_y[i] = b

                    if ((z_min + b * z_interval) <= coor_z[i]) and ((z_min + (b + 1) * z_interval) >= coor_z[i]):
                        data_save_z[i] = b

**Comment by ShougangShen** [comment]
Sorry, This repo is specifically set for myself, and may not suit your needs.
